name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-pinned.txt
        pip install black isort flake8 mypy bandit safety pytest-cov
    - name: Lint and format
      run: |
        black --check .
        isort --check-only .
        flake8 .
        mypy src tests
    - name: Security scan
      run: |
        bandit -r src/
        safety check -r requirements-pinned.txt
    - name: Test
      run: |
        pytest --cov=src tests/
        python hyperparameter_tuning.py --help
    - name: Verify imports and basic functionality
      run: |
        python -c "from core.controller import Controller; print('Import successful')"
        python -c "import numpy as np; from core.controller import Controller; from src.kernel.config_loader import load_config; config = load_config([]); controller = Controller(config); X_train = np.array([[1], [2], [3]]); y_train = np.array([[2], [4], [6]]); controller.train(X_train, y_train); print('Training successful')"
